### ISSUE TITLE
consider using dry-rest-permissions instead of guardians

### ISSUE THREAD

**Issue by auvipy** [cycloidio/cyclosible#13]

**Comment by Seraf** [comment]
Hello,

This package doesn't provide the granularity we need for our customers: https://github.com/Helioscene/dry-rest-permissions/issues/9

We currently have some customers who are able to run a playbook but some users just have the right to view deployments. The package dry-rest-permissions can't provide that.

Anyway, it's planned to add a permissions api to directly configure them with the API : #2
