### ISSUE TITLE
Why should I need mysql if I prefer postgres?

### ISSUE THREAD

**Issue by auvipy** [cycloidio/cyclosible#18]
Collecting Cyclosible
  Downloading cyclosible-0.3.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): djangorestframework in /usr/local/lib/python2.7/dist-packages (from Cyclosible)
Requirement already satisfied (use --upgrade to upgrade): django>=1.8 in /usr/local/lib/python2.7/dist-packages (from Cyclosible)
Collecting mysqlclient (from Cyclosible)
  Downloading mysqlclient-1.3.7.tar.gz (79kB)
    100% |████████████████████████████████| 81kB 274kB/s 
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-bX9o9l/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-bX9o9l/mysqlclient

**Comment by Seraf** [comment]
That's a good point, I need to remove this dependencie

**Comment by Seraf** [comment]
@auvipy https://pypi.python.org/pypi/cyclosible/0.3.2 should fix your problem

**Comment by auvipy** [comment]
thank you!
